# Generated by Django 4.2.3 on 2023-07-16 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0004_tag"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="tags",
            field=models.ManyToManyField(to="courses.tag"),
        ),
    ]
